version: "3.7"
services:
  api:
    container_name: car_service
    build: .
    command: pipenv run python ./car_service.py
    ports:
      -  8000:8000
    networks:
      - api

networks:
  api:
    driver: bridge
